file: "temp.tif"
geoserver:
  enabled: true # Si está a True, publica el dato en geoserver
  style: "goyas:temp" # Activods de momento: goyas:RGB_Composition, goyas:chl, goyas:temp

title: "El Val - Temperature"
abstract: "Temperatura del agua en el embalse El Val"
contact:
  individualName: "Daniel García Díaz"
  organisationName: "IFCA-CSIC"
  email: "garciad@ifca.unican.es"
provenance: "Fuente de datos XYZ"
preprocessing:
  method: "ACOLITE 20250114.0"
  pid: "https://github.com/acolite/acolite/releases/tag/20250114.0"
processing:
  - description: "algoritmoX"
    title: "TitleX"
    reference: "idX"
  - description: "algoritmoY"
    title: "TitleY"
    reference: "idY"

coverage:
  temporal:
    begin: "2022-06-15"
    end: "2022-06-15"
  spatial:
    auto: true # Calculado a partir del dataset
    # Si auto es false, se usan estos valores:
    west: -111.4564
    east: -102.4564
    south: 39.1428
    north: 46.1428

resolution:
  x: 10
  y: 10

keywords:
  theme: "Water; Temp; Temperature"
  place: "El Val; Zaragoza"

license:
  type: "Creative Commons 4.0"

parameters:
  temp:
    name: "Temperature"
    definition: "Water Temperature"
    unit: "celsius"
    error: "0.05"
    precision: "0.01"
