file: "Example_CdP_Sentinel-2_L2A_NDWI.tif"
geonetwork:
  url: "https://goyas.csic.es/geonetwork"
  username: ""
  password: ""
storage:
  endpoint_url: "https://api.cloud.ifca.es:8080"
  access_key: ""
  secret_key: ""
  bucket: ""
geoserver:
  url: "https://goyas.csic.es/geoserver"
  workspace: "goyas"
  username: ""
  password: ""
  enabled: true # Si está a True, publica el dato en geoserver
  style: "goyas:temp" # Activods de momento: goyas:RGB_Composition, goyas:chl, goyas:temp

title: "Test S3"
abstract: "Temperatura del agua en el embalse El Val"
contact:
  individualName: "Fernando Aguilar"
  organisationName: "IFCA-CSIC"
  email: "aguilarf@ifca.unican.es"
provenance: "Fuente de datos XYZ"
preprocessing:
  method: "ACOLITE 20250114.0"
  pid: "https://github.com/acolite/acolite/releases/tag/20250114.0"
processing:
  - description: "algoritmoX"
    title: "TitleX"
    reference: "idX"
  - description: "algoritmoY"
    title: "TitleY"
    reference: "idY"

coverage:
  temporal:
    begin: "2022-06-15"
    end: "2022-06-15"
  spatial:
    auto: true # Calculado a partir del dataset
    # Si auto es false, se usan estos valores:
    west: -111.4564
    east: -102.4564
    south: 39.1428
    north: 46.1428

resolution:
  x: 10
  y: 10

keywords:
  theme: "Water; NDWI"
  place: "CdP; Cuerda del Pozo; Vinuesa"

license:
  type: "Creative Commons 4.0"

parameters:
  temp:
    name: "Temperature"
    definition: "Water Temperature"
    unit: "celsius"
    error: "0.05"
    precision: "0.01"
